//! Per-N blocklists of T11 column-stratified-weight-profile hashes that
//! map to ≥ 2 distinct canonical forms.
//!
//! The T11 cache tier (see `enumerate.rs::canon_info`) trusts cache hits
//! for any hash NOT in the per-N blocklist. Blocklisted hashes fall
//! through to nauty unconditionally. Const arrays here are generated by
//! the `dump_t11_blocklist` binary (run after `compute_t11_hash` is
//! finalised). Regenerate any time `canon::compute_t11_hash` changes —
//! the hash function and the blocklist values are coupled.
//!
//! Empirical sizes (verified by `scripts/dump_t11_blocklist.py`
//! 2026-05-18):
//! - N ≤ 14: zero collisions observed (empty blocklists OK).
//! - N = 16:    1 colliding hash  /    146 classes.
//! - N = 18:    1 colliding hash  /    341 classes.
//! - N = 20:   19 colliding hashes / 1 211 classes.
//! - N = 22:   30 colliding hashes / 5 118 classes (worst bucket = 2).
//! - N = 24: 1364 colliding hashes / 37 496 classes (worst bucket = 14).
//! - N ≥ 26: T11 collision rate grows faster than linear; no blocklist
//!           provided. The class-fingerprint cache is disabled at
//!           unknown N (`t11_enabled` derives from this).

#![cfg(feature = "t11_cache")]

use rustc_hash::FxHashSet;

/// T11 collision hash at N = 16. Generated by
/// `scripts/dump_t11_blocklist.py --N 16`.
pub const T11_BLOCKLIST_N16: &[u64] = &[
    0xd4ce2a4c6231244c,
];

/// T11 collision hash at N = 18. Generated by
/// `scripts/dump_t11_blocklist.py --N 18`.
pub const T11_BLOCKLIST_N18: &[u64] = &[
    0x08dc2b1849b7c7bc,
];

/// T11 collision hashes at N = 20. Generated by
/// `scripts/dump_t11_blocklist.py --N 20`.
///
/// 19 hashes / 1211 canonical classes; worst bucket = 2.
pub const T11_BLOCKLIST_N20: &[u64] = &[
    0x02609515b0bb1e85, 0x0f030e7db349cf14,
    0x1e9344756a1bf4a5, 0x20175221680a016d,
    0x2485a7696bb5795a, 0x291016c08fa312d9,
    0x55a106de8738c991, 0x579c6ce7e840a3bd,
    0x79a51831e89f5f13, 0x88b175b28ea68313,
    0x8ad357c245419e55, 0x947c186fe8280fbc,
    0xa46af291c74326cf, 0xb8ee3cd0689781d1,
    0xd40c3a3c698d7e0b, 0xd9181c2f696f52f7,
    0xdae323dfc7c91d68, 0xe19c8f3a475c304f,
    0xf096b645d7f326fb,
];

/// T11 collision hashes at N = 22. Generated by
/// `scripts/dump_t11_blocklist.py --N 22`.
///
/// 30 hashes / 5118 canonical classes; worst bucket = 2 (always pairs).
pub const T11_BLOCKLIST_N22: &[u64] = &[
    0x054d51a39c53e59c, 0x05bbadb48ccab0b7,
    0x09e66996943e4089, 0x0e2b0ac713e14845,
    0x128abd5b12b877a8, 0x1b1501d7cc40865c,
    0x1f5348840ecc3931, 0x256987b99be77a3b,
    0x2dd075a293b0f7c0, 0x36fce1bb9327e9bd,
    0x521adf27901de5f7, 0x55cb79d20f522fca,
    0x5726c11a93ffbae3, 0x5c84e52c8ee542b1,
    0x66943a24a23931d6, 0x7818481b9f998f85,
    0x86bbd7f2995a3184, 0x87bef3a19222fa13,
    0x935e515a9be8e213, 0x9ca1e96090ac5c90,
    0x9e25f70c929a6958, 0xa2944c549245e145,
    0xaa450aa4953ad04e, 0xcb1b78ee987bb904,
    0xcd32b6eb13f9956e, 0xd0895cd0cec1dbf2,
    0xd5ab11d312d10ba8, 0xd9f8d61e9a460d1e,
    0xf7b3bd1d132fc6fe, 0xffac7082997d96ce,
];

/// T11 collision hashes at N = 24. Generated by
/// `scripts/dump_t11_blocklist.py --N 24`.
///
/// 1364 hashes / 37 496 canonical classes; worst bucket = 14. The wider
/// buckets degrade the cache hit rate vs N = 22 but the cache is still
/// a net win — first-encounter hashes get cached, blocklisted ones
/// fall through to nauty, no hash collides into wrong-class assignment.
pub const T11_BLOCKLIST_N24: &[u64] = include!("t11_blocklist_n24.in");

/// Materialise the blocklist for the requested N, or `None` if T11 is
/// not validated at that N (caller should disable the T11 cache).
///
/// Ns enumerated in `T11_VALIDATED_NS` below have empirically zero
/// collisions and so accept an empty blocklist safely. Ns past N = 24
/// have not been audited; callers MUST fall through to the pre-T11
/// flow rather than risk wrong-class identification.
pub fn t11_blocklist_for_n(n: u32) -> Option<FxHashSet<u64>> {
    match n {
        // N ≤ 14: empirically zero collisions.
        4..=14 => Some(FxHashSet::default()),
        16 => Some(T11_BLOCKLIST_N16.iter().copied().collect()),
        18 => Some(T11_BLOCKLIST_N18.iter().copied().collect()),
        20 => Some(T11_BLOCKLIST_N20.iter().copied().collect()),
        22 => Some(T11_BLOCKLIST_N22.iter().copied().collect()),
        24 => Some(T11_BLOCKLIST_N24.iter().copied().collect()),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn blocklist_present_for_validated_ns() {
        for n in [4u32, 8, 14, 16, 18, 20, 22, 24] {
            assert!(
                t11_blocklist_for_n(n).is_some(),
                "blocklist must exist for validated N={}",
                n,
            );
        }
    }

    #[test]
    fn unknown_n_returns_none() {
        assert!(t11_blocklist_for_n(26).is_none());
        assert!(t11_blocklist_for_n(28).is_none());
        assert!(t11_blocklist_for_n(0).is_none());
    }

    #[test]
    fn const_arrays_are_dedup_and_sorted() {
        // Catches accidental duplicates in the hand-pasted blocklists.
        for &arr in &[
            T11_BLOCKLIST_N16,
            T11_BLOCKLIST_N18,
            T11_BLOCKLIST_N20,
            T11_BLOCKLIST_N22,
            T11_BLOCKLIST_N24,
        ] {
            let mut copy: Vec<u64> = arr.to_vec();
            copy.sort_unstable();
            copy.dedup();
            assert_eq!(copy.len(), arr.len(), "blocklist contains duplicates");
        }
    }

    #[test]
    fn blocklist_sizes_match_audit() {
        // Empirical sizes from `scripts/dump_t11_blocklist.py` 2026-05-18.
        // A mismatch means either the dump produced different values (hash
        // function changed) or someone hand-edited the const arrays.
        assert_eq!(T11_BLOCKLIST_N16.len(), 1);
        assert_eq!(T11_BLOCKLIST_N18.len(), 1);
        assert_eq!(T11_BLOCKLIST_N20.len(), 19);
        assert_eq!(T11_BLOCKLIST_N22.len(), 30);
        assert_eq!(T11_BLOCKLIST_N24.len(), 1364);
    }
}
