"""Specialised enumerator for doubly-even [N, k] codes via GL(k, 2)-orbits
of column multiplicity functions (§5 reformulation).

A [N, k] doubly-even code is equivalently a function M : F_2^k -> Z_>=0 with:
    sum_v M(v) = N
    for every u != 0:  sum_{v : u . v = 1} M(v)  ≡  0 (mod 4)
    support({v : M(v) > 0}) spans F_2^k             (full rank k)

Two codes are permutation-equivalent iff their multiplicity functions lie in
the same GL(k, 2)-orbit under (M, A) -> M . A.

Bottlenecks:
- enumerate_de_multisets: a 2^k-position DFS with codeword-weight pruning.
- orbit_count: BFS over GL(k, 2) generated by k transvections + one cyclic
  permutation; orbit size in the multiset DAG.
"""

from __future__ import annotations

import argparse
import time
from itertools import product


def popcount(x: int) -> int:
    return bin(x).count("1")


def _u_set(k: int) -> list[list[int]]:
    """For each v in F_2^k, the list of u in F_2^k \ {0} with u . v == 1.

    Used by the DFS to update codeword-weight accumulators on assignment."""
    nv = 1 << k
    out: list[list[int]] = []
    for v in range(nv):
        out.append([u for u in range(1, nv) if popcount(u & v) & 1])
    return out


def enumerate_de_multisets(N: int, k: int) -> list[tuple[int, ...]]:
    """Yield all doubly-even multiplicity vectors of total weight N, full rank k.

    DFS over (m_0, m_1, ..., m_{2^k - 1}). Pruning:
    - per-u codeword-weight upper bound (w[u] <= N).
    - final check: each w[u] ≡ 0 mod 4.
    - rank check: after DFS, support spans F_2^k.
    """
    nv = 1 << k
    us_for_v = _u_set(k)

    M = [0] * nv
    w = [0] * nv  # codeword weights, indexed by u
    results: list[tuple[int, ...]] = []

    def recurse(idx: int, remaining: int) -> None:
        if idx == nv:
            if remaining == 0:
                for u in range(1, nv):
                    if w[u] & 3:
                        return
                results.append(tuple(M))
            return
        us = us_for_v[idx]
        for m in range(remaining + 1):
            M[idx] = m
            ok = True
            for u in us:
                w[u] += m
                if w[u] > N:
                    ok = False
            if ok:
                recurse(idx + 1, remaining - m)
            for u in us:
                w[u] -= m
        M[idx] = 0

    recurse(0, N)
    return results


def spans_full(M: tuple[int, ...], k: int) -> bool:
    """{v : M[v] > 0} spans F_2^k."""
    nv = 1 << k
    rows: list[int] = []
    rank = 0
    for v in range(nv):
        if M[v] == 0:
            continue
        x = v
        for r in rows:
            lb = r & -r
            if x & lb:
                x ^= r
        if x:
            rows.append(x)
            rank += 1
            if rank == k:
                return True
    return False


def gl_generators(k: int):
    """A spanning generator set for GL(k, 2) as functions F_2^k -> F_2^k.

    For k == 1, GL(1, 2) is trivial — return [].
    For k >= 2: transvection T_{0,1} + cyclic shift; for k >= 2 we add the
    bit-0 ↔ bit-1 swap as a safety net so the union-find converges faster.
    """
    if k <= 1:
        return []
    nv = 1 << k
    mask = nv - 1

    def transvect(v: int) -> int:  # v + v_1 * e_0
        if (v >> 1) & 1:
            return v ^ 1
        return v

    def cyclic(v: int) -> int:  # cyclic shift of bits
        return ((v << 1) | (v >> (k - 1))) & mask

    def swap01(v: int) -> int:  # transpose bit 0 and bit 1
        b0 = v & 1
        b1 = (v >> 1) & 1
        if b0 == b1:
            return v
        return v ^ 0b11

    return [transvect, cyclic, swap01]


def count_orbits(multisets: list[tuple[int, ...]], k: int) -> int:
    """Count GL(k, 2)-orbits via BFS in the Cayley graph induced by the generators."""
    nv = 1 << k
    gens = gl_generators(k)
    multiset_set = set(multisets)
    visited: set[tuple[int, ...]] = set()
    n_orbits = 0
    for M in multisets:
        if M in visited:
            continue
        n_orbits += 1
        # BFS from M
        stack = [M]
        while stack:
            cur = stack.pop()
            if cur in visited:
                continue
            visited.add(cur)
            for g in gens:
                neigh = tuple(cur[g(v)] for v in range(nv))
                if neigh in multiset_set and neigh not in visited:
                    stack.append(neigh)
    return n_orbits


def count_classes(N: int, k: int) -> tuple[int, int, float, float]:
    t0 = time.time()
    all_multisets = enumerate_de_multisets(N, k)
    t_enum = time.time() - t0
    full_rank = [M for M in all_multisets if spans_full(M, k)]
    t0 = time.time()
    n_orbits = count_orbits(full_rank, k)
    t_orbit = time.time() - t0
    return n_orbits, len(full_rank), t_enum, t_orbit


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--N", type=str, default="8,12,16,20,24,28,32")
    parser.add_argument("--k", type=str, default="1,2,3,4")
    args = parser.parse_args()
    Ns = [int(n) for n in args.N.split(",")]
    Ks = [int(k) for k in args.k.split(",")]

    print(f"\n{'(N, k)':>10} {'classes':>10} {'multisets':>12} {'enum(s)':>10} {'orbit(s)':>10}", flush=True)
    for N in Ns:
        for k in Ks:
            if k > N:
                continue
            n_classes, n_multisets, t_e, t_o = count_classes(N, k)
            print(
                f"{(N, k)!s:>10} {n_classes:>10} {n_multisets:>12} {t_e:>10.3f} {t_o:>10.3f}",
                flush=True,
            )


if __name__ == "__main__":
    main()
